# Site settings
title: Magnus Skare
description: The Portfolio of Magnus Skare.
baseurl: ""
url: "http://magnusskare.com"
twitter_username: MagnusSkare
github_username:  partcoffee

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed