# Site settings
title: Magnus Skare
email: your-email@domain.com
description: The Portfolio of Magnus Skare.
baseurl: "/about"
url: "http://magnusskare.com"
twitter_username: MagnusSkare
github_username:  partcoffee

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed